const suppliers = [
  {value: 'GEM', name: 'Gemline'},
  {value: 'DIAMONDBACKBRANDING', name: 'Diamondback Branding'},
  {value: 'snugz', name: 'Snugz'},
  {value: 'PCNA', name: 'PCNA'},
  {value: 'HIT', name: 'HIT Promotional Products'},
  {value: 'belpromo', name: 'Belpromo'},
  {value: 'ETS', name: 'ETS Express'},
  {value: 'towelspecialties', name: 'Towel Specialties'},
  {value: 'terry', name: 'Terrytown'},
  {value: 'PEERLESSUMBRELLACO', name: 'Peerless Umbrella Co.'},
  {value: 'POPPROMOS', name: 'Pop! Promos'},
  {value: 'kooziegroup', name: 'Koozie Group (previously BIC Graphic)'},
  {value: 'Hirsch', name: 'Hirsch Gift'},
  {value: 'sign', name: 'Showdown Displays'},
  {value: 'orbus', name: 'Orbus'},
  {value: 'digispec', name: 'Digispec'},
  {value: 'Gold', name: 'Gold Bond World Wide'},
  {value: 'LMRK', name: 'Logomark'},
  {value: 'JOURNALBOOKSTIMEPLANNER', name: 'JOURNALBOOKSTIMEPLANNER'},
  {value: 'Ariel', name: 'Ariel Premium Supply'},
  {value: 'MAG', name: 'The Magnet Group'},
  {value: 'tekweld', name: 'Tekweld'},
  {value: 'CAP', name: 'Cap America'},
  //   {value: 'STOUSE', name: 'Stouse'},// no product info available
  {value: 'RainingRose', name: 'Raining Rose'},
  {value: 'SS', name: 'S&S Activewear'},
  {value: 'SanMar', name: 'SanMar'},
  {value: 'alphabroder', name: 'Alphabroder'},
]

export default suppliers
