name: pr

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  prepare-node-modules:
    uses: ./.github/workflows/_prepare-node-modules.yml
    secrets: inherit

  create-build-cache:
    needs: prepare-node-modules
    uses: ./.github/workflows/_create-build-cache.yml
    secrets: inherit

  run-eslint:
    needs: prepare-node-modules
    uses: ./.github/workflows/_run-eslint.yml

  run-pr-code-checks:
    # needs: [prepare-node-modules, prepare-cms-node-modules]
    needs: prepare-node-modules
    uses: ./.github/workflows/_run-pr-code-checks.yml

  test_job:
    runs-on: ubuntu-latest
    name: A job to test eslint-changeset action
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout main
          git checkout ${{ github.head_ref }}
      - name: Eslint Changeset Step
        uses: esrimo/gh-action-eslint-changeset@v1
        id: eslint-changeset
        with:
          main-branch: 'main'
          file-extension: 'js|jsx|ts|tsx'

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,jsx,tsx,html,css,md,yml}
          only_changed: True
