name: pr

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  prepare-node-modules:
    uses: ./.github/workflows/_prepare-node-modules.yml
    secrets: inherit

  # prepare-cms-node-modules:
  #   uses: ./.github/workflows/_prepare-cms-node-modules.yml
  #   secrets: inherit

  create-build-cache:
    needs: prepare-node-modules
    uses: ./.github/workflows/_create-build-cache.yml
    secrets: inherit

  run-eslint:
    needs: prepare-node-modules
    uses: ./.github/workflows/_run-eslint.yml

  run-pr-code-checks:
    # needs: [prepare-node-modules, prepare-cms-node-modules]
    needs: prepare-node-modules
    uses: ./.github/workflows/_run-pr-code-checks.yml

  # run-performance-checks:
  #   needs: [prepare-node-modules, create-build-cache]
  #   uses: ./.github/workflows/_run-performance-checks.yml

  # run-gitleaks:
  #   needs: prepare-node-modules
  #   uses: ./.github/workflows/_run-gitleaks.yml

  # run-unit-tests:
  #   needs: prepare-node-modules
  #   uses: ./.github/workflows/_run-unit-tests.yml

  # run-functional-tests:
  #   needs: [prepare-node-modules, create-build-cache]
  #   uses: ./.github/workflows/_run-functional-tests.yml

  # deploy-pr-preview:
  #   uses: ./.github/workflows/_deploy-app-to-s3.yml
  #   needs: [prepare-node-modules, create-build-cache]
  #   secrets: inherit
  #   with:
  #     app-name: pr
  #     env-names: base mock build s3-upload
